name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Make
        run: make

  release:
    needs: [ make ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Run semantic-release
        run: make semantic-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup ko
        if: github.event_name == 'push'
        uses: imjasonh/setup-ko@v0.4
        with:
          version: v0.8.0

      - name: Publish
        if: github.event_name == 'push'
        run: ko publish . -t ${{ steps.release.outputs.TAG_NAME }} --bare
