name: Publish Docker Image
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version Number"
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish . -t ${{ github.event.inputs.version }} --bare
